server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: simple-ecommerce-api
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL:jdbc:mariadb://db:3306/simple_ecommerce?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin123}
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
  task:
    execution:
      thread-name-prefix: ecommerce-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: ecommerce-scheduling-
      pool:
        size: 2

application:
  base-portal-url: ${BASE_PORTAL_URL:http://localhost:3000}
  security:
    jwt:
      secret: ${JWT_SECRET:X85CsAp6jk0slfJ2r67b0zy8IGPK/Zx6Pi6QT9Of76zy0zGws4cEF1Gn52LAaLxC1tbgVi5hQTTEks1tjZTinQ==}
    mfa:
      issuer: ${MFA_ISSUER:localhost}
  cors:
    allowed-origins: 'http://localhost:3000,https://localhost:3000,http://localhost:9000,https://localhost:9000'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-Is-Token-Expired,X-User-Access-Token,X-User-Refresh-Token'
    allow-credentials: true
    max-age: 1800
